### ISSUE TITLE
Create a color picker dialog box for selecting brush color.

### ISSUE THREAD

**Issue by rishidyno** [iiitl/undraw#1]
Suggest a color third party lib for implementing this feature.  

You can use this library https://github.com/jaredrummler/ColorPicker

**Comment by Smarshal21** [comment]
@yash10019coder @rishidyno sir could you please assign this issue to me

**Comment by Smarshal21** [comment]
@yash10019coder @rishidyno  i have the solution for this issue could you please assign it to me so that i could create a pr for this issue ?

**Comment by Smarshal21** [comment]
@rishidyno Can we use this library
https://github.com/yukuku/ambilwarna
I have completed adding the colour picker dialog using this library and ready make a PR on this issue

**Comment by RockingRishav** [comment]
@rishidyno sir, I would like to work upon this issue , pLease assign me.

**Comment by rishidyno** [comment]
Assigned this to @Smarshal21 as he was one to ask first.
