### ISSUE TITLE
Add sharing feature to share canvas to others directly from app.

### ISSUE THREAD

**Issue by rishidyno** [iiitl/undraw#4]

**Comment by Smarshal21** [comment]
@yash10019coder @rishidyno sir could you please assign this issue to me

**Comment by yash10019coder** [comment]
Sure @Smarshal21 assigned

**Comment by rishidyno** [comment]
@Smarshal21 Please let us know if you have any doubts before proceeding with this issue or need any clarification on anything.

**Comment by Smarshal21** [comment]
Ok sir

**Comment by RockingRishav** [comment]
@rishidyno , @yash10019coder sir may i work upon this issue?

**Comment by rishidyno** [comment]
I think @Smarshal21 is inactive, So you can start working on this.
